### ISSUE TITLE
Refine rapidoc visual documentation

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/vetiver-r#89]
In #86 we set up some customized rapidoc with the hex sticker, etc:

![RapiDocFinal](https://user-images.githubusercontent.com/12505835/164050198-e5cb19b8-3288-4622-aa65-0ccbdc5606b2.png)

We should come back and refine this at some point for better accessibility. Specifically:

- the endpoint description (like "Health check") does not have enough contrast
- could add alt text for the logo?
- could try to keep the containers from filling the whole page width:

```css
.m-markdown p:not(:first-child) {
    margin-block-start: 24px;
    max-width: 80ch;
}
```
